# Generated by Django 4.1.1 on 2022-09-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='vpass',
        ),
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.SmallIntegerField(max_length=4, null=True),
        ),
    ]
