# Generated by Django 4.1.1 on 2022-10-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_couraseduration_requiredfields_courseduration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemes',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
