# Generated by Django 4.1.1 on 2022-10-06 10:34

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_vpass_user_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('deptid', models.AutoField(primary_key=True, serialize=False)),
                ('deptname', models.TimeField(max_length=50)),
                ('city', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentHead',
            fields=[
                ('dhid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('deptid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.department')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_status',
        ),
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('caste', models.CharField(max_length=255)),
                ('income', models.IntegerField()),
                ('maritialstatus', models.CharField(max_length=10)),
                ('uid', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schemes',
            fields=[
                ('schemeid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('addedby', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.departmenthead')),
            ],
        ),
        migrations.CreateModel(
            name='RequiredFields',
            fields=[
                ('rfid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.BooleanField(default=False)),
                ('mobile', models.BooleanField(default=False)),
                ('dob', models.BooleanField(default=False)),
                ('gender', models.BooleanField(default=False)),
                ('address', models.BooleanField(default=False)),
                ('marital_status', models.BooleanField(default=False)),
                ('nationality', models.BooleanField(default=False)),
                ('disabilitycert', models.BooleanField(default=False)),
                ('income', models.BooleanField(default=False)),
                ('lastacquired', models.BooleanField(default=False)),
                ('caste', models.BooleanField(default=False)),
                ('schemeid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.schemes')),
            ],
        ),
        migrations.CreateModel(
            name='RequiredDocs',
            fields=[
                ('rdid', models.AutoField(primary_key=True, serialize=False)),
                ('docname', models.CharField(max_length=50)),
                ('uri', models.CharField(max_length=50)),
                ('schemeid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.schemes')),
            ],
        ),
        migrations.CreateModel(
            name='CitizenDocs',
            fields=[
                ('docsid', models.AutoField(primary_key=True, serialize=False)),
                ('auid', models.SmallIntegerField(default=None)),
                ('aname', models.CharField(default=None, max_length=50, null=True)),
                ('agender', models.CharField(default=None, max_length=1, null=True)),
                ('aaddress', models.CharField(default=None, max_length=255, null=True)),
                ('adob', models.DateField(default=None, null=True)),
                ('incomecertificate', models.FileField(default=None, upload_to=api.models.CitizenDocs.use_directory_path)),
                ('rationcard', models.FileField(default=None, upload_to=api.models.CitizenDocs.use_directory_path)),
                ('noncreamylayer', models.FileField(default=None, upload_to=api.models.CitizenDocs.use_directory_path)),
                ('marksheet10', models.FileField(default=None, upload_to=api.models.CitizenDocs.use_directory_path)),
                ('marksheet12', models.FileField(default=None, upload_to=api.models.CitizenDocs.use_directory_path)),
                ('disabilitycert', models.FileField(default=None, upload_to=api.models.CitizenDocs.use_directory_path)),
                ('schemeid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.schemes')),
                ('uid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppliedSchemes',
            fields=[
                ('asid', models.AutoField(primary_key=True, serialize=False)),
                ('schemeid', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.schemes')),
                ('uid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
