# Generated by Django 4.1.1 on 2022-10-06 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_department_departmenthead_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='sid',
            new_name='uid',
        ),
    ]
